name: Auto-Release

on:
  workflow_run:
    workflows: ["Commit Checks"]
    types: [completed]

jobs:
  createRelease:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Download Artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: gradle.yml
        path: "."

    - name: Create Release
      id: createRelease
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact: ./${{ github.event.repository.name }}/${{ github.event.repository.name }}.jar
        artifactContentType: application/zip

        tag: "snapshot"
        name: "Bleeding-Edge Release"
        omitBody: true
        draft: true
        prerelease: true
        allowUpdates: true