name: Auto-Release

on:
  workflow_run:
    workflows: ["Commit Checks"]
    types: [completed]

jobs:
  createRelease:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.5

      - name: Download jar
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: gradle.yml
          path: "."

      - name: Get latest commit
        id: getCommit
        uses: actions/checkout@v2
        with:
          ref: master
          path: ${{ github.event.repository.name }}

      - name: Run kotlin code
        run: kotlinc -script workflows/main.kts ${{ github.event.workflow_run.head_sha }}

      - name: Sleep to allow for python to create output.json
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Confirm existence of output.json
        run: ls workflows/

      - name: Get description string
        uses: pCYSl5EDgo/cat@master
        id: getDescription
        with:
          path: ./workflows/output.json

      - name: Create release
        id: createRelease
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ github.event.repository.name }}/${{ github.event.repository.name }}.jar
          artifactContentType: application/zip

          tag: "dev"
          name: "Bleeding-Edge Release"
          body: "${{ steps.getDescription.outputs.text }}"
          draft: true
          prerelease: true
          allowUpdates: true
